import {useEffect,useRef,useState} from 'react';
import {apiRequest,postJson} from '../../app/api';
import {trackProductEvent} from '../../telemetry';
import './scenes.css';
import {SceneProp} from './SceneProp';
import {ScenePicker} from './ScenePicker';
import {createSceneCard} from './sceneCard';
const defaultMoment=(turns=[])=>{const index=turns.findIndex(turn=>typeof turn.event==='string'&&turn.event.trim());return index>=0?index:Math.max(0,turns.length-1)};
const read=(key)=>{try{return JSON.parse(sessionStorage.getItem(key))||{}}catch{return {}}};
const save=(key,value)=>{try{sessionStorage.setItem(key,JSON.stringify(value))}catch{}};
export function ScenePage({sceneId,shareCode,onNavigate}){
 const [catalog,setCatalog]=useState(null);const [source,setSource]=useState(null);const [loadError,setLoadError]=useState('');
 useEffect(()=>{let live=true;Promise.all([apiRequest('/api/scenes'),shareCode?apiRequest(`/api/scenes/shares/${encodeURIComponent(shareCode)}`):Promise.resolve(null)]).then(([c,s])=>{if(live){setCatalog(c);setSource(s)}}).catch(e=>{if(live)setLoadError(e.message)});return()=>{live=false}},[shareCode]);
 if(loadError)return <main className="scene-page"><h1>现场暂时没打开</h1><p role="alert">{loadError}</p><button className="outline-button" onClick={()=>window.location.reload()}>重新打开</button></main>;
 if(!catalog)return <main className="scene-page" aria-busy="true"><p role="status">正在打开现场…</p></main>;
 const selected=catalog.scenes?.find(s=>s.id===(source?.sceneId||sceneId));
 if(!catalog.enabled||!selected)return <main className="scene-page"><h1>这个现场暂未开放</h1><button className="primary-button" onClick={()=>onNavigate('hao')}>回豪气宇宙</button></main>;
 return <SceneRun key={`${selected.id}:${shareCode||'solo'}`} scene={selected} scenes={catalog.scenes} source={source} shareCode={shareCode} onSourceRevoked={()=>setSource({sceneId:selected.id,available:false})} onNavigate={onNavigate}/>;
}
function SceneRun({scene,scenes,source,shareCode,onSourceRevoked,onNavigate}){
 const [ownerBusy,setOwnerBusy]=useState(false),[ownerError,setOwnerError]=useState('');
 const revokeSource=async()=>{if(ownerBusy)return;setOwnerBusy(true);setOwnerError('');try{await apiRequest(`/api/scenes/shares/${encodeURIComponent(shareCode)}`,{method:'DELETE'});onSourceRevoked();trackProductEvent('scene_share_revoked',{sceneId:scene.id})}catch(e){setOwnerError(e.message)}finally{setOwnerBusy(false)}};
 const key=`hao-scene:${scene.id}:${shareCode||'solo'}`;const initial=useRef(read(key)).current;
 const [run,setRun]=useState(initial.run||null),[input,setInput]=useState(initial.input||''),[pending,setPending]=useState(initial.pending||null),[restartRequired,setRestartRequired]=useState(initial.restartRequired||false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[angle,setAngle]=useState(''),[momentIndex,setMomentIndex]=useState(()=>{const saved=initial.share?.momentIndex ?? initial.momentIndex;return Number.isInteger(saved)&&saved>=0&&saved<(initial.run?.turns?.length||0)?saved:defaultMoment(initial.run?.turns)}),[share,setShare]=useState(initial.share||null),[notice,setNotice]=useState(''),[sharing,setSharing]=useState(false);
 const dialog=useRef(null),generation=useRef(0),lock=useRef(false),lastTurn=useRef(null);
 useEffect(()=>{trackProductEvent('scene_started',{sceneId:scene.id,fromShare:!!shareCode});return()=>{generation.current++}},[]);
 useEffect(()=>{save(key,{run,input,pending,share,restartRequired,momentIndex})},[key,run,input,pending,share,restartRequired,momentIndex]);
 useEffect(()=>{if(run?.turn)lastTurn.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[run?.turn]);
 const submit=async(action)=>{
  if(lock.current||restartRequired)return;const body=pending ? { ...pending, idempotencyKey: pending.retryable ? crypto.randomUUID() : pending.idempotencyKey } : {sceneId:scene.id,input:action==='end'?(input.trim()||'我先撤了'):input.trim(),...(run?.token?{token:run.token}:{}),idempotencyKey:crypto.randomUUID(),...(action==='end'?{action:'end'}:{})};delete body.retryable;if(!body.input)return;
  lock.current=true;setBusy(true);setError('');setPending(body);save(key,{run,input:body.input,pending:body,share,momentIndex});const version=generation.current;
  try{const result=await postJson('/api/scenes/turn',body,{signal:AbortSignal.timeout(30000)});if(version!==generation.current)return;if(!result.token||!Array.isArray(result.turns)||!['playing','completed'].includes(result.status))throw new Error('回应没有完整送达，请重试这次出招。');setRun(result);setInput('');setPending(null);setAngle('');setMomentIndex(defaultMoment(result.turns));trackProductEvent('scene_turn_completed',{sceneId:scene.id,turn:result.turn,status:result.status});if(result.status==='completed')trackProductEvent(shareCode?'scene_recipient_completed':'scene_completed',{sceneId:scene.id});}
  catch(e){if(version===generation.current){if(e.runExpired||e.code==='SCENE_RESULT_UNCERTAIN')setRestartRequired(true);else if(e.retryable)setPending({...body,retryable:true});else if(e.status>=400&&e.status<500&&![408,409,429].includes(e.status))setPending(null);setError(e.name==='TimeoutError'?'等了有点久，结果尚未确认。你的原话已保留，可重试查询这次出招。':e.message)}}finally{if(version===generation.current){lock.current=false;setBusy(false)}}
 };
 const replay=()=>{generation.current++;lock.current=false;setRun(null);setInput('');setPending(null);setRestartRequired(false);setBusy(false);setError('');setShare(null);setNotice('');trackProductEvent('scene_replayed',{sceneId:scene.id})};
 const photoIntro=!run?.turn && (run?.sceneView ?? scene.initialView)?.kind==='photo';
 const rawFacts=run?.sceneFacts ?? scene.initialFacts;
 const facts=Array.isArray(rawFacts)?rawFacts.filter(fact=>typeof fact==='string'&&fact.trim()):[];
 const moment=run?.turns?.[momentIndex];
 const closingInput=run?.turns?.length && momentIndex!==run.turns.length-1 ? run.turns.at(-1).input : '';
 const ending=run?.ending === run?.turns?.at(-1)?.reply ? '' : run?.ending;
 const confirmShare=async()=>{if(sharing||share)return;setSharing(true);setNotice('');try{const result=await postJson('/api/scenes/shares',{token:run.token,momentIndex,confirmed:true,includeClosingInput:momentIndex!==run.turns.length-1});setShare({...result,momentIndex});trackProductEvent('scene_share_confirmed',{sceneId:scene.id})}catch(e){setNotice(e.message)}finally{setSharing(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(new URL(share.url,window.location.origin).href);setNotice('挑战链接已复制。');trackProductEvent('scene_share_copied',{sceneId:scene.id})}catch{setNotice('复制受限，请长按下方链接复制。')}};
 const revoke=async()=>{try{await apiRequest(`/api/scenes/shares/${share.code}`,{method:'DELETE'});setShare(null);setNotice('链接已撤销，原来的链接不再显示你的内容。');trackProductEvent('scene_share_revoked',{sceneId:scene.id})}catch(e){setNotice(e.message)}};
 const download=async()=>{try{const {canvas}=await createSceneCard({scene,moment,ending:run.ending,closingInput,lastReply:run.turns.at(-1)?.reply,shareUrl:share?.url,origin:window.location.origin});const a=document.createElement('a');a.download='我的名场面.png';a.href=canvas.toDataURL();a.click();trackProductEvent('scene_card_downloaded',{sceneId:scene.id});}catch{setNotice('卡片暂时没有生成，请再试一次。')}};
 return <main className={`scene-page ${photoIntro ? 'scene-photo-intro' : ''}`}>
  <div className="scene-topline"><button className="text-button" onClick={()=>onNavigate('hao')}>← 豪气宇宙</button><span>拆台、捧场，都由你</span></div>
  <section className={`scene-opening ${photoIntro ? 'scene-opening-full' : ''}`}><div><span className="scene-label">{scene.category || '日常小事'}</span><h1>{scene.title}</h1><p>{scene.opening}</p>{typeof scene.evidence === 'string' && scene.evidence.trim() ? <aside className="scene-evidence"><strong>你看见的</strong><span>{scene.evidence}</span></aside> : null}</div>{!photoIntro ? <img src={scene.asset||'/assets/jiahao/hao-universe-hero.webp'} alt=""/> : null}</section>
  {source&&!source.available?<p className="scene-note">原来的分享已过期或撤销，你仍然可以挑战同一个现场。</p>:shareCode?<p className="scene-note">朋友给你留了一招。先演你的版本，收场后再看 TA 怎么接。</p>:null}
  {source?.available&&source.isOwner?<div><button className="text-button" disabled={ownerBusy} onClick={revokeSource}>{ownerBusy?"正在撤销…":"撤销我的公开链接"}</button>{ownerError?<p role="alert">{ownerError}</p>:null}</div>:null}
  <div className="scene-turns" aria-live="polite">{run?.turns.map((t,i)=><article className="scene-turn" key={i} ref={i===run.turns.length-1?lastTurn:null}><small>第 {i+1} 招</small><blockquote>我：{t.input}</blockquote><p className="scene-reply">{t.reply}</p>{t.event ? <p className="scene-event">{t.event}</p> : null}</article>)}</div>
  <SceneProp view={run?.sceneView ?? scene.initialView} facts={facts}/>
  {run?.status!=='completed'?<section className="scene-composer"><div className="scene-composer-title"><h2>你怎么接？</h2><span>第 {(run?.turn||0)+1} / 3 招</span></div><div className="scene-angles" aria-label="出招方向">{(run?.angles||scene.angles||[]).map(a=><button key={a} type="button" aria-pressed={angle===a} disabled={busy||!!pending} onClick={()=>setAngle(a)}>{a}</button>)}</div>{angle?<p className="scene-note">想{angle}？用自己的话说就行。</p>:null}<label htmlFor="scene-input">你怎么接招</label><textarea id="scene-input" value={input} maxLength={500} disabled={busy||!!pending} onChange={e=>setInput(e.target.value)} placeholder="你会怎么说？一个字也行。"/><div className="scene-actions"><button className="primary-button" disabled={busy||restartRequired||(!pending&&!input.trim())} onClick={()=>submit()}>{busy?'正在接招…':pending?'重试这次出招':'出招'}</button>{run?.turn > 0 ? <button className="text-button" disabled={busy||!!pending} onClick={()=>submit('end')}>就到这里，收场</button> : null}</div>{busy?<p role="status">正在回复，稍等一下。</p>:null}{restartRequired?<button className="outline-button" onClick={replay}>重新开一局</button>:pending&&!busy?<p className="scene-note">{pending.retryable?'这次未能完成。点击重试会重新生成这一招。':'上次结果还没确认。先重试这次出招，不会另开一招。'}</p>:null}{error?<p role="alert" className="form-message error">{error}</p>:null}<small className="scene-note">回复由 AI 生成，仅供娱乐。刷新后可以继续。</small></section>:<section className="scene-finale"><span className="scene-label">后来</span><h2>{ending||'这次就聊到这儿。'}</h2>{source?.available&&source.moment?<div className="scene-comparison"><article><h3>朋友的名场面</h3><blockquote>{source.moment.input}</blockquote><p>{source.moment.reply}</p>{source.moment.event?<p>{source.moment.event}</p>:null}{source.moment.closingInput?<p>我最后说：{source.moment.closingInput}</p>:null}{source.ending!==source.moment.reply?<strong>{source.ending}</strong>:null}</article><article><h3>你的收场</h3><p>{run.turns.at(-1)?.reply}</p></article></div>:null}<label htmlFor="scene-highlight">想留下哪一句？</label><select id="scene-highlight" value={momentIndex} disabled={!!share} onChange={e=>setMomentIndex(Number(e.target.value))}>{run.turns.map((t,i)=><option key={i} value={i}>第 {i+1} 招 · {t.input.slice(0,25)}</option>)}</select><div className="scene-actions"><button className="primary-button" onClick={()=>{setNotice('');dialog.current.showModal()}}>让朋友接这招</button><button className="outline-button" onClick={replay}>再试一种回答</button></div><button className="text-button" onClick={()=>onNavigate('friends')}>和朋友一起玩七日联赛 →</button></section>}
  <details className="scene-switch"><summary>换个场景</summary><ScenePicker scenes={scenes} currentSceneId={scene.id} onChoose={id=>onNavigate('scenes',id)}/></details>
  <dialog ref={dialog} className="scene-share-dialog" aria-labelledby="scene-share-title" onCancel={()=>trackProductEvent('scene_share_cancelled',{sceneId:scene.id})}><h2 id="scene-share-title">选中的一招和收场将公开</h2><p className="scene-note">任何拿到链接的人都能查看。七天后失效，你也可以主动撤销。</p>{moment?<div className="scene-share-preview"><h3>{scene.title}</h3><p>{scene.opening}</p>{typeof scene.evidence === 'string' && scene.evidence.trim() ? <p>你看见的：{scene.evidence}</p> : null}<blockquote>我：{moment.input}</blockquote><p>{moment.reply}</p>{moment.event?<p>{moment.event}</p>:null}{closingInput?<p>我最后说：{closingInput}</p>:null}{run.ending&&run.ending!==moment.reply?<strong>收场：{run.ending}</strong>:null}</div>:null}<div className="scene-actions">{share?<><button className="primary-button" onClick={copy}>复制挑战链接</button><button className="text-button" onClick={revoke}>撤销公开链接</button></>:<button className="primary-button" disabled={sharing} onClick={confirmShare}>{sharing?'正在生成…':'确认公开并生成链接'}</button>}<button className="outline-button" onClick={download}>下载名场面卡</button><button className="text-button" onClick={()=>{dialog.current.close();trackProductEvent('scene_share_cancelled',{sceneId:scene.id})}}>关闭预览</button></div>{share?<p className="scene-share-url">{new URL(share.url,window.location.origin).href}</p>:null}{notice?<p role="status">{notice}</p>:null}</dialog>
 </main>
}
