import { test, expect } from '@playwright/test';
import {SCENES} from '../../server/scene-catalog.mjs';
import {readFile} from 'node:fs/promises';
const scene={category:'工作',id:'wrong-group',title:'消息发错群',opening:'你把吐槽老板的话发进了工作群，嘉豪正在输入。',character:'嘉豪',angles:['认怂','装镇定']};
async function setup(page){
 await page.route('**/api/**', async r=>{const p=new URL(r.request().url()).pathname;if(p==='/api/scenes')return r.fulfill({json:{enabled:true,scenes:[scene,{...SCENES.find(s=>s.id==='photo'),initialView:{kind:'photo',filter:true,present:true}},{...scene,id:'class-question',category:'校园',title:'课堂走神被点名',opening:'老师突然叫你回答问题。'},{...scene,id:'work-report',category:'工作',title:'汇报没准备',opening:'轮到你汇报了。'},{...scene,id:'friend-dinner',category:'朋友',title:'朋友聚餐',opening:'朋友问今晚谁请客。'}]}});return r.fulfill({json:{rooms:[]}})});
}
test('旧消息场景三回合，刷新恢复，分享确认前不公开',async({page})=>{
 await setup(page);let turns=[];let published=0;
 await page.route('**/api/scenes/turn',async r=>{const b=r.request().postDataJSON();turns.push({input:b.input,reply:`嘉豪：你说「${b.input}」，老板已经截图。`,event:'老板把截图设成了群公告。'});await r.fulfill({json:{sceneId:scene.id,runId:'r1',turn:turns.length,status:turns.length===3?'completed':'playing',reply:turns.at(-1).reply,event:turns.at(-1).event,angles:scene.angles,ending:turns.length===3?'截图成了本周例会封面。':null,turns,token:`token${turns.length}`}})});
 await page.route('**/api/scenes/shares',async r=>{published++;await r.fulfill({json:{code:'abc',url:'/s/abc',expiresAt:'2026-09-12'}})});
 await page.goto('/play/wrong-group');await expect(page).toHaveURL(/play\/wrong-group/);
 await page.getByLabel('你怎么接招').fill('哦');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.locator('.scene-turns').getByText('嘉豪：你说「哦」，老板已经截图。')).toBeVisible();
 await page.reload();await expect(page.locator('.scene-turns').getByText('嘉豪：你说「哦」，老板已经截图。')).toBeVisible();
 for(const input of ['发错了','我投屏道歉']){await page.getByLabel('你怎么接招').fill(input);await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.locator(".scene-turns").getByText(`嘉豪：你说「${input}」，老板已经截图。`)).toBeVisible();}
 await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(published).toBe(0);const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'下载名场面卡'}).click();const png=await readFile(await (await downloadEvent).path());expect(png.subarray(1,4).toString()).toBe('PNG');expect(png.readUInt32BE(16)).toBe(1080);expect(png.readUInt32BE(20)).toBeGreaterThanOrEqual(1200);expect(published).toBe(0);await page.getByRole('button',{name:'确认公开并生成链接'}).click();await expect(page.getByRole('button',{name:'复制挑战链接'})).toBeVisible();expect(published).toBe(1);
});
test('失败不前进且刷新后重试沿用幂等键',async({page})=>{await setup(page);const keys=[];await page.route('**/api/scenes/turn',r=>{keys.push(r.request().postDataJSON().idempotencyKey);return r.fulfill({status:503,json:{error:'这次没有接上'}})});await page.goto('/play/wrong-group');await page.getByLabel('你怎么接招').fill('是我');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.getByRole('alert')).toContainText('这次没有接上');await page.reload();await expect(page.getByLabel('你怎么接招')).toHaveValue('是我');await page.getByRole('button',{name:'重试这次出招'}).click();await expect(page.getByRole('alert')).toContainText('这次没有接上');expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);});
test('分享接收方先玩再看，过期仍保留现场；手机无横向溢出',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.route('**/api/scenes/shares/friend',r=>r.fulfill({json:{sceneId:scene.id,available:true,moment:{input:'我在测试群纪律',reply:'纪律先把你测试了。',event:'你成了纪律委员。'},ending:'纪律委员先写检讨。'}}));await page.goto('/s/friend');await expect(page.getByLabel('你怎么接招')).toBeVisible();await expect(page.getByText('纪律委员先写检讨。')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'r2',turn:1,status:'completed',reply:'好，散会。',event:'你退出了现场。',angles:[],ending:'你先下班。',turns:[{input:'我先撤了',reply:'好，散会。',event:'你退出了现场。'}],token:'end'}}));await page.getByLabel('你怎么接招').fill('我先撤了');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.getByText('纪律委员先写检讨。')).toBeVisible();await page.route('**/api/scenes/shares/expired',r=>r.fulfill({json:{sceneId:scene.id,available:false}}));await page.goto('/s/expired');await expect(page.getByText('这条分享已过期或撤销，原来的内容不再显示。你还可以玩这一题。')).toBeVisible();await expect(page.getByLabel('你怎么接招')).toBeVisible();});
test('明确输入错误后能够改字重新出招',async({page})=>{await setup(page);await page.route('**/api/scenes/turn',r=>r.fulfill({status:400,json:{error:'请修改输入'}}));await page.goto('/play/wrong-group');await page.getByLabel('你怎么接招').fill('坏输入');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.getByRole('alert')).toContainText('请修改输入');await expect(page.getByLabel('你怎么接招')).toBeEnabled();});
test('已确认模型失败由玩家手动重试新键，重启过期可新开一局',async({page})=>{await setup(page);const keys=[];await page.route('**/api/scenes/turn',r=>{keys.push(r.request().postDataJSON().idempotencyKey);return r.fulfill({status:503,json:{error:'模型未完成',code:'SCENE_PROVIDER_FAILED',retryable:true}})});await page.goto('/play/wrong-group');await page.getByLabel('你怎么接招').fill('试试');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.getByRole('alert')).toContainText('模型未完成');await page.getByRole('button',{name:'重试这次出招'}).click();await expect.poll(()=>keys.length).toBe(2);expect(keys[0]).not.toBe(keys[1]);await page.route('**/api/scenes/turn',r=>r.fulfill({status:409,json:{error:'本局已过期',code:'SCENE_RESTARTED',runExpired:true,retryable:false}}));await page.getByRole('button',{name:'重试这次出招'}).click();await page.getByRole('button',{name:'重新开一局'}).click();await expect(page.getByLabel('你怎么接招')).toBeEnabled();await expect(page.getByLabel('你怎么接招')).toHaveValue('');});
test('首招不提供无效收场，已有招数收场按钮手机可触达',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.goto('/play/wrong-group');await expect(page.getByLabel('你怎么接招')).toBeVisible();await expect(page.getByRole('button',{name:'就聊到这儿'})).toHaveCount(0);await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'first',turn:1,status:'playing',reply:'老板看到了。',event:'群里安静了。',angles:[],ending:null,turns:[{input:'哦',reply:'老板看到了。',event:'群里安静了。'}],token:'first'}}));await page.getByLabel('你怎么接招').fill('哦');await page.getByRole('button',{name:'出招',exact:true}).click();const end=page.getByRole('button',{name:'就聊到这儿'});await end.scrollIntoViewIfNeeded();await expect(end).toBeInViewport();expect(await end.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})).toBe(true);});
test('名场面PNG在公开前后均可下载，下载不会偷偷公开',async({page})=>{
 await setup(page);let published=0;
 await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'card',turn:1,status:'completed',reply:'奶龙：教材还附赠考勤记录。',event:'大家开始划重点。',angles:[],ending:'你成为了本周案例。',turns:[{input:'我来做反面教材',reply:'奶龙：教材还附赠考勤记录。',event:'大家开始划重点。'}],token:'card-token'}}));
 await page.route('**/api/scenes/shares',r=>{published++;return r.fulfill({json:{code:'confirmed',url:'/s/confirmed',expiresAt:'2026-09-12'}})});
 await page.goto('/play/wrong-group');await page.getByLabel('你怎么接招').fill('我来做反面教材');await page.getByRole('button',{name:'出招',exact:true}).click();await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();
 const images=[];
 for(const confirmed of [false,true]){
  if(confirmed){await page.getByRole('button',{name:'确认公开并生成链接'}).click();await expect(page.getByRole('button',{name:'复制挑战链接'})).toBeVisible();}
  const event=page.waitForEvent('download');await page.getByRole('button',{name:'下载名场面卡'}).click();const png=await readFile(await (await event).path());expect(png.subarray(1,4).toString()).toBe('PNG');expect(png.readUInt32BE(16)).toBe(1080);expect(png.readUInt32BE(20)).toBeGreaterThanOrEqual(1200);expect(published).toBe(confirmed?1:0);images.push(png);
 }
 expect(images[0].equals(images[1])).toBe(false);
});
test('创建者打开自己的链接即可撤销，其他人没有撤销入口',async({page})=>{
 await setup(page);let removed=0;await page.route('**/api/scenes/shares/owner',r=>{if(r.request().method()==='DELETE'){removed++;return r.fulfill({json:{ok:true}})}return r.fulfill({json:{sceneId:scene.id,available:true,isOwner:true,moment:{input:'这是我的原句',reply:'私有高光',event:'现场变化'},ending:'结尾'}})});
 await page.goto('/s/owner');await page.getByRole('button',{name:'撤销我的公开链接'}).click();await expect(page.getByText('这条分享已过期或撤销，原来的内容不再显示。你还可以玩这一题。')).toBeVisible();expect(removed).toBe(1);await expect(page.getByLabel('你怎么接招')).toBeVisible();await expect(page.getByText('这是我的原句')).toHaveCount(0);
 await page.route('**/api/scenes/shares/other',r=>r.fulfill({json:{sceneId:scene.id,available:true,isOwner:false,moment:{input:'别人的原句',reply:'其他高光',event:'变化'},ending:'尾声'}}));await page.goto('/s/other');await expect(page.getByLabel('你怎么接招')).toBeVisible();await expect(page.getByRole('button',{name:'撤销我的公开链接'})).toHaveCount(0);
});
test('首页默认自拍，也能按校园工作朋友选择并在游戏内换题',async({page})=>{await setup(page);await page.goto('/');await page.getByRole('button',{name:'先接一招',exact:false}).click();await expect(page).toHaveURL(/play\/photo/);await expect(page.getByRole('heading',{name:'嘉豪坚持原片直出',exact:true})).toBeVisible();await page.getByRole('button',{name:'豪气宇宙',exact:false}).first().click();const picker=page.getByRole('region',{name:'挑个你熟悉的场景'});await picker.getByRole('button',{name:'工作',exact:true}).click();await expect(picker.getByRole('button',{name:'汇报没准备',exact:false})).toBeVisible();await expect(picker.getByRole('button',{name:'课堂走神被点名',exact:false})).toHaveCount(0);await picker.getByRole('button',{name:'汇报没准备',exact:false}).click();await expect(page).toHaveURL(/play\/work-report/);await page.getByText('换个场景', {exact:true}).click();const inGame=page.getByRole('region',{name:'挑个你熟悉的场景'});await inGame.getByRole('button',{name:'朋友',exact:true}).click();await inGame.getByRole('button',{name:'朋友聚餐',exact:false}).click();await expect(page).toHaveURL(/play\/friend-dinner/);});
test('最后回复即结尾时不重复，空旁白不占位置',async({page})=>{await setup(page);await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'plain',turn:1,status:'completed',reply:'同桌把书往你这边推了推。',event:'',angles:[],ending:'同桌把书往你这边推了推。',turns:[{input:'第几页',reply:'同桌把书往你这边推了推。',event:''}],token:'plain-token'}}));await page.goto('/play/wrong-group');await page.getByLabel('你怎么接招').fill('第几页');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.locator('.scene-turns')).toContainText('同桌把书往你这边推了推。');await expect(page.locator('.scene-event')).toHaveCount(0);await expect(page.locator('.scene-finale')).not.toContainText('同桌把书往你这边推了推。');});
test('开场展示已有可见证据，没有证据字段时不凭空补充',async({page})=>{await setup(page);await page.route('**/api/scenes',r=>r.fulfill({json:{enabled:true,scenes:[{...scene,evidence:'嘉豪摊开的是英语书，黑板上写着数学题。'}]}}));await page.goto('/play/wrong-group');await expect(page.getByText('你看见的',{exact:true})).toBeVisible();await expect(page.getByText('嘉豪摊开的是英语书，黑板上写着数学题。',{exact:true})).toBeVisible();await page.unroute('**/api/scenes');await page.reload();await expect(page.getByLabel('你怎么接招')).toBeVisible();await expect(page.getByText('你看见的',{exact:true})).toHaveCount(0);});
test('分享预览与下载卡保留开场证据，不额外公开会话',async({page})=>{await setup(page);await page.route('**/api/scenes',r=>r.fulfill({json:{enabled:true,scenes:[{...scene,evidence:'你看见他拿着英语书讲数学。'}]}}));await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'evidence-card',turn:1,status:'completed',reply:'嘉豪把书翻到了封底。',event:'',angles:[],ending:'嘉豪把书翻到了封底。',turns:[{input:'你拿的什么书',reply:'嘉豪把书翻到了封底。',event:''}],token:'evidence-card'}}));await page.goto('/play/wrong-group');await page.getByLabel('你怎么接招').fill('你拿的什么书');await page.getByRole('button',{name:'出招',exact:true}).click();await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('你看见他拿着英语书讲数学。');const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载名场面卡'}).click();const png=await readFile(await (await download).path());expect(png.readUInt32BE(16)).toBe(1080);expect(png.readUInt32BE(20)).toBeGreaterThanOrEqual(1200);});
test('眼前情况从初始事实更新并刷新保留，旧场景不造状态板',async({page})=>{await page.setViewportSize({width:390,height:844});await setup(page);await page.route('**/api/scenes',r=>r.fulfill({json:{enabled:true,scenes:[{...scene,initialFacts:['文档还是空的。']}]}}));await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'facts',turn:1,status:'playing',reply:'嘉豪：我写好了。',event:'嘉豪写下第一行。',angles:[],ending:null,sceneFacts:['文档正文：\n第一行已经写好。'],turns:[{input:'写一行看看',reply:'嘉豪：我写好了。',event:'嘉豪写下第一行。'}],token:'facts-token'}}));await page.goto('/play/wrong-group');await expect(page.getByRole('region',{name:'眼前情况'})).toContainText('文档还是空的。');await page.getByLabel('你怎么接招').fill('写一行看看');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.getByRole('region',{name:'眼前情况'})).toContainText('第一行已经写好。');await expect(page.getByRole('region',{name:'眼前情况'})).not.toContainText('文档还是空的。');await page.reload();await expect(page.getByRole('region',{name:'眼前情况'})).toContainText('第一行已经写好。');await page.unroute('**/api/scenes');await page.goto('/play/class-question');await expect(page.getByLabel('你怎么接招')).toBeVisible();await expect(page.getByRole('region',{name:'眼前情况'})).toHaveCount(0);});
test('道具纸页显示实际正文且刷新保留',async({page})=>{await setup(page);await page.route('**/api/scenes',r=>r.fulfill({json:{enabled:true,scenes:[{...scene,initialView:{kind:'document',lines:[]},initialFacts:['空文档']} ]}}));await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'prop',turn:1,status:'playing',reply:'写了一行。',event:'',angles:[],ending:null,sceneView:{kind:'document',lines:['第一行：开题原因','第二行：实施办法']},sceneFacts:['重复事实'],turns:[{input:'写吧',reply:'写了一行。',event:''}],token:'prop'}}));await page.goto('/play/wrong-group');await expect(page.getByRole('region',{name:'文档'})).toContainText('还没有正文');await page.getByLabel('你怎么接招').fill('写吧');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.getByRole('region',{name:'文档'})).toContainText('第二行：实施办法');await expect(page.getByRole('region',{name:'眼前情况'})).toHaveCount(0);await page.reload();await expect(page.getByRole('region',{name:'文档'})).toContainText('第一行：开题原因');});
test('相框示意按公开状态关闭滤镜和删除，不冒充照片处理',async({page})=>{await setup(page);await page.route('**/api/scenes',r=>r.fulfill({json:{enabled:true,scenes:[{...scene,initialView:{kind:'photo',filter:true,present:true}}]}}));let turn=0;await page.route('**/api/scenes/turn',r=>{turn++;return r.fulfill({json:{sceneId:scene.id,runId:'photo-prop',turn,status:'playing',reply:'好了。',event:'',angles:[],ending:null,sceneView:{kind:'photo',filter:false,present:turn===1},turns:[{input:'改一下',reply:'好了。',event:''}],token:`photo${turn}`}})});await page.goto('/play/wrong-group');const frame=page.getByRole('region',{name:'相框示意'});await expect(frame).toContainText('滤镜开启');await expect(frame.locator('img')).toBeVisible();await expect(frame).toContainText('门框弯了');for(const [input,expected] of [['关滤镜','滤镜关闭'],['删掉','照片已删除']]){await page.getByLabel('你怎么接招').fill(input);await page.getByRole('button',{name:'出招',exact:true}).click();await expect(frame).toContainText(expected)}await expect(frame.locator('img')).toHaveCount(0);});
test('手机自拍首招不滚动就能看到输入入口',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.route('**/api/scenes',r=>r.fulfill({json:{enabled:true,scenes:[{...SCENES.find(s=>s.id==='photo'),initialView:{kind:'photo',filter:true,present:true}}]}}));await page.goto('/play/photo');await expect(page.getByRole('region',{name:'相框示意'})).toBeVisible();expect(await page.evaluate(()=>window.scrollY)).toBe(0);await expect(page.locator('label[for="scene-input"]')).toBeInViewport();expect(await page.locator('label[for="scene-input"]').evaluate(el=>el.getBoundingClientRect().bottom < document.querySelector('.mobile-nav').getBoundingClientRect().top)).toBe(true);await page.screenshot({path:'/tmp/scene-photo-mobile-first.png'});});
test('选择第一招分享时预览包含实际会公开的最后收场',async({page})=>{await setup(page);await page.addInitScript(()=>sessionStorage.setItem('hao-scene:wrong-group:solo',JSON.stringify({run:{sceneId:'wrong-group',runId:'preview',turn:3,status:'completed',token:'preview',ending:'最后他把滤镜关了。',turns:[{input:'第一句',reply:'最初还嘴硬。',event:''},{input:'第二句',reply:'还在找借口。',event:''},{input:'第三句',reply:'最后他把滤镜关了。',event:''}]}})));await page.goto('/play/wrong-group');await page.getByLabel('想留下哪一句？').selectOption('0');await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('最初还嘴硬。');await expect(page.getByRole('dialog')).toContainText('收场：最后他把滤镜关了。');await page.getByRole('button',{name:'关闭预览'}).click();await page.getByLabel('想留下哪一句？').selectOption('2');await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog').getByText('最后他把滤镜关了。',{exact:true})).toHaveCount(1);await expect(page.getByRole('dialog')).not.toContainText('收场：');});
test('完成后默认分享首个实际动作并保留不同收场',async({page})=>{await setup(page);let turn=0;const turns=[{input:'真的假的',reply:'真的。',event:''},{input:'关掉滤镜',reply:'我就给你看看。',event:'嘉豪关闭了滤镜，门框恢复直线。'},{input:'现在呢',reply:'门框都证明我没动手脚。',event:''}];await page.route('**/api/scenes/turn',r=>{turn++;return r.fulfill({json:{sceneId:scene.id,runId:'moment-default',turn,status:turn===3?'completed':'playing',reply:turns[turn-1].reply,event:turns[turn-1].event,angles:[],ending:turn===3?'门框都证明我没动手脚。':null,turns:turns.slice(0,turn),token:`moment-${turn}`}})});await page.goto('/play/wrong-group');for(const t of turns){await page.getByLabel('你怎么接招').fill(t.input);await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.locator('.scene-turns')).toContainText(t.reply)}await expect(page.getByLabel('想留下哪一句？')).toHaveValue('1');await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();const preview=page.getByRole('dialog');await expect(preview).toContainText('我：关掉滤镜');await expect(preview).toContainText('嘉豪关闭了滤镜，门框恢复直线。');await expect(preview).toContainText('收场：门框都证明我没动手脚。');});
test('手动高光确认后刷新仍预览同一招，确认前允许修改',async({page})=>{await setup(page);await page.addInitScript(()=>{if(!sessionStorage.getItem('hao-scene:wrong-group:solo'))sessionStorage.setItem('hao-scene:wrong-group:solo',JSON.stringify({run:{sceneId:'wrong-group',runId:'saved-choice',turn:3,status:'completed',token:'choice-token',ending:'末句',turns:[{input:'第一句',reply:'第一答',event:'先做了动作'},{input:'第二句',reply:'第二答',event:''},{input:'第三句',reply:'第三答',event:''}]}}))});await page.route('**/api/scenes/shares',r=>r.fulfill({json:{code:'choice-share',url:'/s/choice-share'}}));await page.goto('/play/wrong-group');const select=page.getByLabel('想留下哪一句？');await select.selectOption('1');await expect(select).toBeEnabled();await select.selectOption('2');await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await page.getByRole('button',{name:'确认公开并生成链接'}).click();await expect(page.getByRole('button',{name:'复制挑战链接'})).toBeVisible();await page.reload();await expect(select).toHaveValue('2');await expect(select).toBeDisabled();await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('我：第三句');await expect(page.getByRole('dialog')).not.toContainText('我：第一句');});
test('分享非末招时明示最后输入，末招不重复收场上下文',async({page})=>{await setup(page);await page.addInitScript(()=>{window.cardText=[];const draw=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){window.cardText.push(String(text));return draw.call(this,text,...args)}});await page.addInitScript(()=>sessionStorage.setItem('hao-scene:wrong-group:solo',JSON.stringify({run:{sceneId:'wrong-group',turn:3,status:'completed',token:'closing',ending:'最佳摄影我收着。',turns:[{input:'关滤镜',reply:'关就关',event:'关了滤镜'},{input:'好多了',reply:'那当然',event:''},{input:'给你颁最佳摄影',reply:'最佳摄影我收着。',event:''}]}})));await page.goto('/play/wrong-group');await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('看看要分享的内容');await expect(page.getByRole('dialog')).toContainText('我最后说：给你颁最佳摄影');const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载名场面卡'}).click();await download;expect(await page.evaluate(()=>window.cardText.join(''))).toContain('我最后说：给你颁最佳摄影');await page.getByRole('button',{name:'关闭预览'}).click();await page.getByLabel('想留下哪一句？').selectOption('2');await page.getByRole('button',{name:'让朋友接这招',exact:true}).click();await expect(page.getByRole('dialog')).not.toContainText('我最后说：');});
test('接收方对照保留公开收场输入',async({page})=>{await setup(page);await page.route('**/api/scenes/shares/context',r=>r.fulfill({json:{sceneId:scene.id,available:true,moment:{input:'关滤镜',reply:'关就关',event:'滤镜关闭',closingInput:'给你颁最佳摄影'},ending:'最佳摄影我收着。'}}));await page.route('**/api/scenes/turn',r=>r.fulfill({json:{sceneId:scene.id,runId:'recipient',turn:1,status:'completed',reply:'行吧',ending:'行吧',event:'',turns:[{input:'行',reply:'行吧',event:''}],token:'recipient'}}));await page.goto('/s/context');await page.getByLabel('你怎么接招').fill('行');await page.getByRole('button',{name:'出招',exact:true}).click();await expect(page.locator('.scene-comparison')).toContainText('我最后说：给你颁最佳摄影');});
